language: c
before_install:
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
- sleep 3
- export DISPLAY=:1.0
- wget http://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz
- tar xf arduino-1.8.5-linux64.tar.xz
- sudo mv arduino-1.8.5 /usr/local/share/arduino
- sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
- arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json"
  --save-prefs
- git clone https://github.com/tzapu/WiFiManager.git /home/travis/Arduino/libraries/WiFiManager
- arduino --install-boards esp8266:esp8266
- arduino --board esp8266:esp8266:generic --save-prefs
- arduino --pref "compiler.warning_level=all" --save-prefs
script:
- echo $PWD
- echo $HOME
- ls $PWD
- source $TRAVIS_BUILD_DIR/travis/common.sh
- build
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: change
    on_failure: change
before_deploy:
- zip LcdTcpBin.zip /tmp/mkESP/LcdTcp_nodemcuv2/LcdTcp.bin /tmp/mkESP/LcdTcp_nodemcuv2/LcdTcp.elf
deploy:
  provider: releases
  api_key:
    secure: EyER/b6D3A3sCSpH4//S9QIBb94hEACc8sZpYokcvoAXfOYeUH/dFXIlPzYElr45x4hXp7dJWUERQj+N7eNA9BnnzFz1GgUqXBtqs7PQ4R/kL03VSMqj75x1qTfg7TUeVzIREMGQjMEChFabYMrJRDN4klSgRH9Z5XIsRHIWMir6LIL4Fva3fBHSJbemYtJpb6SsMMjPw3/lyltsr2zwgwNnxsKCWzqlRlClrkybvpub7qKPaLDmsBuLsB+4MrzcqZHC+DckTp08wH4Zyi8MzlqfvH5SakNkM9vPc4taMlIcgvIoOZdGYBHkf6jmcSRypd7H/S0kLOUTrn9m/nr2gqjnTfx46FiQoiuUVxcGXhCZmchi9yGSLrJT4SbZBTLIz0KAEwqyOK3lKCDvCPPs0AaZeTFkBwzIHN/oaIqi4wPJ/9NEvYxW6Tq9MaewCb42NSHxmxy3RNUKi2Cldw+ewCWSSmi7xf+7CyLYgEyVmfbpr0cqy2cyrR1wv2LPmA10PhfAZymc9w4/C3kQhl+h9wrN66quAuKClQnipLb65Awk4Bfs7wDlYDcbesYTBX6BIaRTg1kwdtIOUzWiQKWdhP1B1GsjYz87Ejf6mRJc1m16umkeevBawEFpNYZZGDE96H/EY1HyB1IOSPGTC7bT43HAMtPOde0j7DLXWSJrcCM=
  file: LcdTcpBin.zip
  skip_cleanup: true
  on:
    repo: eeyrw/LcdTcp
    tags: true
